name: Deploy dev app on Heroku
on:
  push:
    branches: 
      - develop
jobs:
  Build-Docker-Container:
    runs-on: ubuntu-latest
    container: docker-latest
    steps: 
      - uses: actions/checkout@v2
      - name: docker-build
        env: 
          HEROKU_DEV_REGISTRY_URL: ${{secrets.HEROKU_DEV_REGISTRY_URL}}
          HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}}
          HEROKU_API_TOKEN: ${{secrets.HEROKU_API_TOKEN}}
        run: |
          ls
          docker build -f Dockerfile.heroku --iidfile image_id.txt -t $HEROKU_DEV_REGISTRY_URL
          docker login -u $HEROKU_USERNAME --password $HEROKU_TOKEN registry.heroku.com
          cat image_id.txt


